/** Modules generated by the docs Vite plugin (vite-plugin.ts). */
declare module "virtual:fw-docs" {
	import type { Component } from "svelte";
	import type { Docset, PageMeta } from "./discover.mjs";
	export const docsets: Docset[];
	export const pages: PageMeta[];
	export const loaders: Record<string, () => Promise<{ default: Component }>>;
	export const schemas: Record<string, { name: string; schema: JsonSchema }[]>;
	export const errors: { code: string; message: string; hint?: string; docs?: string; file: string; line: number }[];
	/** Per docset: `docs/<set>/glossary.toml`. */
	export const glossary: Record<string, { name: string; aka: string[]; text: string }[]>;
	/** Per docset with `rust`: Tauri commands by file. */
	export const rust: Record<string, { file: string; about: string; commands: { name: string; args: string[]; returns: string; doc: string; line: number }[] }[]>;
	/** Per docset: learning paths (`docs/<set>/paths.toml`); `pages` are page keys. */
	export const paths: Record<string, { id: string; title: string; description: string; minutes: number; pages: string[] }[]>;
	/** The fw developer CLI, from its help text. */
	export const fwCli: { usage: string; text: string }[];
	/** The docs site's version folder ("1.2.0", "next"), or "" when the build is unversioned. */
	export const siteVersion: string;
	/** dev: every docset; prod: ship = "prod" sets; docs: the web site's sets. */
	export const buildMode: "dev" | "prod" | "docs";
	export const loadSearch: () => Promise<{ default: string }>;
	export const loadApi: () => Promise<{ default: Record<string, import("./api.mjs").ApiSymbol[]> }>;
	export interface JsonSchema {
		type?: string | string[];
		title?: string;
		description?: string;
		default?: unknown;
		enum?: unknown[];
		properties?: Record<string, JsonSchema>;
		additionalProperties?: boolean | JsonSchema;
		items?: JsonSchema;
		required?: string[];
	}
}

/** A repository file for <Source> (source.mjs): its highlighted code block. */
declare module "virtual:fw-source/*" {
	const html: string;
	export default html;
}

/** The Svelte runtime the compiler targets (no public types); the playground hands it to compiled components. */
declare module "svelte/internal/client";
