/**
 * Vaults (Section 12.3-12.4): a user chosen folder holding the user's files plus an
 * `.appname/` folder with vault.toml (identity), settings, workspace, keys, menus, plugins, data.
 * Paths through `vault.fs` are relative to the root; Rust rejects escapes on desktop.
 */
import { parse, stringify } from "smol-toml";
import { Emitter, type Disposable } from "../kernel/disposable";
import { FanwitError } from "../kernel/errors";
import type { Kernel } from "../kernel/kernel.svelte";
import type { FsEntry, FsEvent } from "../host/types";
import { basename, joinPath } from "../host/types";
import { identity } from "../gen/identity";

export interface VaultInfo {
	id: string;
	name: string;
	path: string;
	/** `<path>/.appname` */
	configDir: string;
	readonly: boolean;
}

export interface RecentVault {
	id: string;
	name: string;
	path: string;
	lastOpened: number;
	pinned?: boolean;
	missing?: boolean;
}

export interface VetoableEvent {
	veto(reason: string): void;
}

const GITIGNORE = "# generated by the app: volatile and rebuildable files\ncache/\ndata/state.db\ndata/state.db-*\ndata/state.json\nwindows.toml\nlock\n";
const HEARTBEAT = 30_000;

export interface Indexer {
	id: string;
	glob: string;
	parse(path: string, text: string): Record<string, unknown> | Promise<Record<string, unknown>>;
}

/** Glob to RegExp in one pass, so replacements never rewrite each other's output. */
export function globToRegExp(glob: string) {
	let re = "";
	for (let i = 0; i < glob.length; i++) {
		const c = glob[i];
		if (c === "*" && glob[i + 1] === "*") {
			if (glob[i + 2] === "/") {
				re += "(?:.*/)?";
				i += 2;
			} else {
				re += ".*";
				i += 1;
			}
		} else if (c === "*") re += "[^/]*";
		else if (c === "?") re += "[^/]";
		else re += c.replace(/[.+^${}()|[\]\\]/, "\\$&");
	}
	return new RegExp(`^${re}$`);
}

/**
 * Lock owner id: stable across reloads of this window (sessionStorage survives a reload,
 * not a new window or app launch), so a hot reload does not see its own lock as foreign.
 */
function windowInstanceId(): string {
	try {
		const id = sessionStorage.getItem("fanwit:instance") ?? crypto.randomUUID();
		sessionStorage.setItem("fanwit:instance", id);
		return id;
	} catch {
		return crypto.randomUUID();
	}
}

export class VaultService {
	current = $state<VaultInfo | null>(null);
	recentList = $state<RecentVault[]>([]);
	readonly onDidOpen = new Emitter<VaultInfo>();
	readonly onWillClose = new Emitter<VetoableEvent>();
	readonly onDidClose = new Emitter<void>();
	private instance = windowInstanceId();
	/** Opened with attach: the lock belongs to another window of this app. */
	private attached = false;
	private heartbeat: ReturnType<typeof setInterval> | undefined;
	private ignore: RegExp[] = [];
	readonly folder = identity.vaultFolder;
	indexers = new Map<string, Indexer>();

	constructor(private k: Kernel) {
		// the main window owns the vault: other windows of this app ask it to open one
		if (k.host.windows.label !== "main") return;
		k.events.on("fw:vault-open" as never, async (m: { id: string; path: string; readonly?: boolean }) => {
			try {
				const info = await this.open(m.path, { readonly: m.readonly });
				k.events.emit("fw:vault-opened" as never, { id: m.id, info: $state.snapshot(info) } as never, { scope: "app" });
			} catch (e) {
				// host errors arrive as plain strings
				const err = e as Partial<FanwitError>;
				k.events.emit("fw:vault-opened" as never, { id: m.id, error: { code: err?.code ?? "VAULT_OPEN", message: String(err?.message ?? e) } } as never, { scope: "app" });
			}
		});
	}

	/**
	 * A fresh lock from another instance id still may be dead: a closed, killed or restarted
	 * app leaves its last heartbeat behind. Desktop asks whether the recorded process runs.
	 */
	private async lockOwnerLive(pid: number | undefined): Promise<boolean> {
		if (!pid || !this.k.host.processAlive) return true;
		// only the main window takes locks, so one from this very process is ours
		if (pid === (await this.k.host.app()).pid) return false;
		return this.k.host.processAlive(pid).catch(() => true);
	}

	/** A secondary window's open: forwarded to the main window, which holds the lock. */
	private openInMain(path: string, readonly?: boolean): Promise<VaultInfo> {
		const id = crypto.randomUUID();
		return new Promise((resolve, reject) => {
			const d = this.k.events.on("fw:vault-opened" as never, (m: { id: string; info?: VaultInfo; error?: { code: string; message: string } }) => {
				if (m.id !== id) return;
				d.dispose();
				if (m.info) resolve(m.info);
				else reject(new FanwitError(m.error?.code ?? "VAULT_OPEN", { message: m.error?.message ?? "The main window could not open the vault." }));
			});
			this.k.events.emit("fw:vault-open" as never, { id, path, readonly } as never, { scope: "app" });
		});
	}

	async loadRecent() {
		this.recentList = (await this.k.sys.storage.get<RecentVault[]>("fanwit", "vaults/recent")) ?? [];
		return this.recentList;
	}

	async recent(): Promise<RecentVault[]> {
		const list = await this.loadRecent();
		for (const v of list) v.missing = !(await this.k.host.fs.exists(v.path).catch(() => false));
		return list;
	}

	private async saveRecent() {
		await this.k.sys.storage.set("fanwit", "vaults/recent", $state.snapshot(this.recentList));
		await this.k.sys.storage.flush();
	}

	async forget(path: string) {
		this.recentList = this.recentList.filter((v) => v.path !== path);
		await this.saveRecent();
	}

	async pin(path: string, on = true) {
		const v = this.recentList.find((x) => x.path === path);
		if (v) v.pinned = on;
		await this.saveRecent();
	}

	/** Open a vault folder; without a path, ask with the folder picker. */
	/**
	 * Open a vault. `attach` is for secondary windows of this app instance: they share the vault
	 * the main window owns, so they skip the lock, the recent list and the indexer.
	 */
	async open(path?: string, o: { readonly?: boolean; attach?: boolean } = {}): Promise<VaultInfo> {
		if (!path) {
			const picked = await this.k.host.fs.pickFolder({ title: "Open folder as vault" });
			if (!picked) throw new FanwitError("CANCELLED", { message: "Cancelled." });
			path = picked;
		}
		path = path.replace(/\\/g, "/").replace(/\/+$/, "");
		if (!o.attach && this.k.host.windows.label !== "main") return this.openInMain(path, o.readonly);
		if (this.current?.path === path) return this.current;
		if (this.current) await this.close();
		const fs = this.k.host.fs;
		await fs.allowRoot(path);
		if (!(await fs.exists(path))) throw new FanwitError("VAULT_MISSING", { message: `The folder ${path} does not exist.`, hint: "It may have been moved or deleted. Locate it or remove it from the list." });
		const configDir = joinPath(path, this.folder);
		await fs.mkdir(configDir);
		await fs.mkdir(joinPath(configDir, "data"));

		// identity: the uuid lets the registry recognise a moved or renamed vault
		const vt = joinPath(configDir, "vault.toml");
		let meta: Record<string, unknown>;
		try {
			meta = parse(await fs.readText(vt));
		} catch {
			meta = { id: crypto.randomUUID(), name: basename(path), created: new Date().toISOString(), app: identity.slug, appVersion: identity.version, schema: 1 };
			await fs.writeText(vt, "# Vault identity. Do not change the id.\n" + stringify(meta) + "\n");
		}
		if (!(await fs.exists(joinPath(configDir, ".gitignore")))) await fs.writeText(joinPath(configDir, ".gitignore"), GITIGNORE);

		// single owner: a lock with instance id and heartbeat
		let readonly = !!o.readonly;
		const lockPath = joinPath(configDir, "lock");
		try {
			const lock = JSON.parse(await fs.readText(lockPath)) as { instance: string; time: number; pid?: number };
			if (!o.attach && !readonly && lock.instance !== this.instance && Date.now() - lock.time < HEARTBEAT * 3 && (await this.lockOwnerLive(lock.pid))) {
				const ok = await this.k.host.dialog.ask(`"${meta.name}" is open in another window or app instance. Open it read only?`, {
					title: "Vault in use",
					okLabel: "Open read only",
					cancelLabel: "Cancel"
				});
				if (!ok) throw new FanwitError("CANCELLED", { message: "Cancelled." });
				readonly = true;
			}
		} catch (e) {
			if ((e as FanwitError).code === "CANCELLED") throw e;
		}
		const info: VaultInfo = { id: String(meta.id), name: String(meta.name ?? basename(path)), path, configDir, readonly };
		this.attached = !!o.attach;
		if (!readonly && !o.attach) {
			const pid = (await this.k.host.app()).pid;
			const beat = () => void fs.writeText(lockPath, JSON.stringify({ instance: this.instance, pid, time: Date.now() })).catch(() => {});
			beat();
			this.heartbeat = setInterval(beat, HEARTBEAT);
		}
		await this.loadIgnore(path);
		// remember it before announcing it: a reload once the vault shows must find it again
		if (!o.attach) {
			const rec = this.recentList.filter((v) => v.path !== path && v.id !== info.id);
			this.recentList = [{ id: info.id, name: info.name, path, lastOpened: Date.now(), pinned: this.recentList.find((v) => v.path === path)?.pinned }, ...rec].slice(0, 30);
			await this.saveRecent();
		}
		this.current = info;
		this.k.context.set("vault.open", true);
		this.k.context.set("vault.name", info.name);
		this.k.context.set("vault.readonly", readonly);
		this.k.sys.storage.setVaultDir(joinPath(configDir, "data"));
		await this.k.sys.settings.setVault(configDir);
		this.onDidOpen.fire(info);
		this.indexWatch?.dispose();
		this.indexWatch = null;
		if (!o.attach) void this.reindex().catch((e) => this.k.scopedLog("vault").warn("indexing failed:", (e as Error).message));
		this.k.events.emit("vault:opened" as never, { name: info.name, path } as never);
		await this.k.modules.fire("onVault", true);
		void this.fireFileEvents();
		return info;
	}

	/** onVaultFile:*.md activation events for globs of files present in the vault. */
	private async fireFileEvents() {
		const files = await this.fs.list("", { recursive: true }).catch(() => []);
		const exts = new Set(files.filter((f) => !f.dir).map((f) => f.name.split(".").pop()));
		for (const e of exts) await this.k.modules.fire(`onVaultFile:*.${e}`);
	}

	async create(o: { parent?: string; name: string; template?: string }): Promise<VaultInfo> {
		let parent = o.parent;
		if (!parent) {
			// web: browser storage (OPFS) unless the caller passes a picked fsa:// folder
			const picked = this.k.host.kind === "browser" ? "/vaults" : await this.k.host.fs.pickFolder({ title: "Choose where to create the vault" });
			if (!picked) throw new FanwitError("CANCELLED", { message: "Cancelled." });
			parent = picked;
		}
		const path = joinPath(parent, o.name.replace(/[\\/:*?"<>|]/g, "-"));
		if (this.k.host.kind !== "browser") await this.k.host.fs.allowRoot(parent);
		await this.k.host.fs.mkdir(path);
		if (o.template) await this.applyTemplate(path, o.template);
		return this.open(path);
	}

	private async applyTemplate(path: string, template: string) {
		const fs = this.k.host.fs;
		const files: Record<string, string> =
			template === "journal"
				? { "Journal/README.md": "# Journal\n\nOne note per day. Use the daily note command.\n" }
				: template === "project"
					? { "README.md": "# Project\n\n## Goals\n\n## Notes\n", "tasks.md": "# Tasks\n\n- [ ] First task\n" }
					: { "Welcome.md": `# Welcome\n\nThis vault was created by ${identity.name}. Your notes stay plain files you own.\n` };
		for (const [p, text] of Object.entries(files)) await fs.writeText(joinPath(path, p), text);
	}

	async close(): Promise<boolean> {
		if (!this.current) return true;
		const reasons: string[] = [];
		this.onWillClose.fire({ veto: (r) => reasons.push(r) });
		if (reasons.length) {
			const ok = await this.k.host.dialog.ask(`Close the vault anyway?\n\n${reasons.join("\n")}`, { title: "Unsaved work", okLabel: "Close vault", kind: "warning" });
			if (!ok) return false;
		}
		await this.k.sys.layout.flush();
		await this.k.sys.settings.flush();
		await this.k.sys.storage.flush();
		clearInterval(this.heartbeat);
		if (!this.current.readonly && !this.attached) await this.k.host.fs.remove(joinPath(this.current.configDir, "lock")).catch(() => {});
		this.current = null;
		this.k.sys.storage.setVaultDir(null);
		await this.k.sys.settings.setVault(null);
		this.k.context.set("vault.open", false);
		this.k.context.set("vault.name", undefined);
		this.onDidClose.fire();
		return true;
	}

	private async loadIgnore(root: string) {
		this.ignore = [/^node_modules(\/|$)/, /^\.git(\/|$)/];
		try {
			const text = await this.k.host.fs.readText(joinPath(root, `.${identity.slug}ignore`));
			for (const line of text.split(/\r?\n/)) {
				const l = line.trim();
				if (!l || l.startsWith("#")) continue;
				const g = l.replace(/^\//, "").replace(/\/$/, "/**");
				this.ignore.push(globToRegExp(g), globToRegExp(g + "/**"));
			}
		} catch {
			/* no ignore file */
		}
	}

	private isIgnored(rel: string, includeConfig: boolean) {
		if (!includeConfig && (rel === this.folder || rel.startsWith(this.folder + "/"))) return true;
		return this.ignore.some((r) => r.test(rel));
	}

	private abs(rel: string) {
		const v = this.current;
		if (!v) throw new FanwitError("VAULT_NONE", { message: "No vault is open.", hint: "Open or create a vault first.", docs: "manual://vaults" });
		const clean = rel.replace(/\\/g, "/").replace(/^\/+/, "");
		if (clean.split("/").includes("..")) throw new FanwitError("PERMISSION_DENIED", { message: `Path "${rel}" escapes the vault.` });
		return clean ? joinPath(v.path, clean) : v.path;
	}

	rel(abs: string) {
		const root = this.current?.path ?? "";
		const a = abs.replace(/\\/g, "/");
		return a.startsWith(root) ? a.slice(root.length).replace(/^\/+/, "") : a;
	}

	/** File system sandboxed to the vault root. */
	readonly fs = {
		read: (p: string) => this.k.host.fs.read(this.abs(p)),
		readText: (p: string) => this.k.host.fs.readText(this.abs(p)),
		write: (p: string, data: string | Uint8Array) => {
			if (this.current?.readonly) throw new FanwitError("VAULT_READONLY", { message: "This vault is open read only." });
			return typeof data === "string" ? this.k.host.fs.writeText(this.abs(p), data, { atomic: true }) : this.k.host.fs.write(this.abs(p), data);
		},
		list: async (dir = "", o: { recursive?: boolean; glob?: string; includeConfig?: boolean } = {}): Promise<FsEntry[]> => {
			const all = await this.k.host.fs.list(this.abs(dir), { recursive: o.recursive });
			const re = o.glob ? globToRegExp(o.glob) : null;
			return all
				.map((e) => ({ ...e, path: this.rel(e.path) }))
				.filter((e) => !this.isIgnored(e.path, !!o.includeConfig) && (!re || e.dir || re.test(e.path)));
		},
		stat: (p: string) => this.k.host.fs.stat(this.abs(p)),
		exists: (p: string) => this.k.host.fs.exists(this.abs(p)),
		mkdir: (p: string) => this.k.host.fs.mkdir(this.abs(p)),
		rename: async (from: string, to: string) => {
			await this.k.host.fs.rename(this.abs(from), this.abs(to));
			this.k.events.emit("vault:renamed" as never, { from, to } as never);
		},
		trash: async (p: string) => {
			const mode = this.k.sys.settings.get<string>("vault.trash");
			if (mode === "vault") await this.k.host.fs.rename(this.abs(p), this.abs(`.trash/${basename(p)}`));
			else await this.k.host.fs.trash(this.abs(p));
		},
		watch: async (glob: string, cb: (e: FsEvent) => void): Promise<Disposable> => {
			const re = globToRegExp(glob);
			return this.k.host.fs.watch(this.abs(""), (events) => {
				for (const e of events) {
					const rel = this.rel(e.path);
					if (this.isIgnored(rel, false) || !re.test(rel)) continue;
					cb({ ...e, path: rel, from: e.from ? this.rel(e.from) : undefined });
				}
			});
		}
	};

	/** App defined metadata indexers (Obsidian style fast queries). */
	/**
	 * Indexers (Section 12.4.1): app defined metadata extracted from vault files, rebuilt
	 * incrementally on change and queryable with SQL (table _fanwit_index in the vault's index.db).
	 */
	readonly index = {
		register: (ix: Indexer) => {
			this.indexers.set(ix.id, ix);
			if (this.current) void this.reindex(ix.id);
			return { dispose: () => this.indexers.delete(ix.id) };
		},
		/** Rows for an indexer, optionally filtered by a JSON path value: query("links", "$.target", "b.md"). */
		query: async (indexer: string, jsonPath?: string, equals?: unknown): Promise<{ path: string; data: Record<string, unknown> }[]> => {
			const db = this.indexDb();
			if (!db) return [];
			const rows = jsonPath
				? await db.query<{ path: string; data: string }>({ text: "SELECT path, data FROM _fanwit_index WHERE indexer = ? AND EXISTS (SELECT 1 FROM json_each(data, ?) WHERE value = ?) ORDER BY path", params: [indexer, jsonPath, equals] }).catch(() => [])
				: await db.query<{ path: string; data: string }>({ text: "SELECT path, data FROM _fanwit_index WHERE indexer = ? ORDER BY path", params: [indexer] });
			return rows.map((r) => ({ path: r.path, data: JSON.parse(r.data) }));
		},
		rebuild: (id?: string) => this.reindex(id)
	};

	private indexWatch: Disposable | null = null;
	private indexDb() {
		if (!this.current || !this.k.host.caps.sql) return null;
		return this.k.sys.db.sql("fanwit", { scope: "vault", file: "index.db" });
	}

	private async indexFile(db: NonNullable<ReturnType<VaultService["indexDb"]>>, ix: Indexer, path: string) {
		const re = globToRegExp(ix.glob);
		if (!re.test(path)) return;
		let data: Record<string, unknown> | null = null;
		try {
			data = await ix.parse(path, await this.fs.readText(path));
		} catch {
			data = null;
		}
		await db.transaction((tx) => {
			tx.exec({ text: "DELETE FROM _fanwit_index WHERE indexer = ? AND path = ?", params: [ix.id, path] });
			if (data) tx.exec({ text: "INSERT INTO _fanwit_index (indexer, path, data) VALUES (?, ?, ?)", params: [ix.id, path, JSON.stringify(data)] });
		});
	}

	private async reindex(only?: string) {
		const db = this.indexDb();
		if (!db || !this.indexers.size) return;
		await db.exec("CREATE TABLE IF NOT EXISTS _fanwit_index (indexer TEXT NOT NULL, path TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY (indexer, path))");
		const files = (await this.fs.list("", { recursive: true }).catch(() => [])).filter((f) => !f.dir);
		const list = [...this.indexers.values()].filter((ix) => !only || ix.id === only);
		await this.k.sys.jobs.run(`Index ${this.current!.name}`, async ({ report }) => {
			for (const ix of list) {
				await db.exec({ text: "DELETE FROM _fanwit_index WHERE indexer = ?", params: [ix.id] });
				for (const [i, f] of files.entries()) {
					await this.indexFile(db, ix, f.path);
					if (i % 20 === 0) report(i / files.length, f.path);
				}
			}
		}, { silent: files.length < 200 });
		this.indexWatch ??= await this.fs.watch("**", async (e) => {
			const d = this.indexDb();
			if (!d) return;
			for (const ix of this.indexers.values()) {
				if (e.kind === "deleted" || e.kind === "renamed") await d.exec({ text: "DELETE FROM _fanwit_index WHERE indexer = ? AND path = ?", params: [ix.id, e.from ?? e.path] }).catch(() => {});
				if (e.kind !== "deleted") await this.indexFile(d, ix, e.path).catch(() => {});
			}
			this.k.events.emit("vault:indexed" as never, { path: e.path } as never);
		});
	}

	async openInNewWindow(path: string) {
		if (!this.k.host.caps.nativeWindows) {
			window.open(`/?vault=${encodeURIComponent(path)}`, "_blank");
			return;
		}
		await this.k.host.windows.open({ label: `main-${Date.now().toString(36)}`, url: `/?vault=${encodeURIComponent(path)}`, title: basename(path), width: 1200, height: 780, visible: false });
	}
}
