// GENERATED by `pnpm fw rename`. Do not edit by hand.
#[allow(dead_code)]
pub const NAME: &str = "Fanwit";
#[allow(dead_code)]
pub const SLUG: &str = "fanwit";
#[allow(dead_code)]
pub const VAULT_FOLDER: &str = ".fanwit";
